[package]
name = "jeanne-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
rusqlite = { version = "0.32", features = ["bundled"] }
sqlite-vec = "0.1"
notify = "6.1"
